<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <groupId>com.club.subject</groupId>
  <artifactId>club-subject</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <description>刷题社区项目领域服务-父模块</description>

  <properties>
    <java.version>21</java.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
  </properties>
  
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.11.0</version>
        <configuration>
          <source>21</source>
          <target>21</target>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <modules>
    <module>club-subject-api</module>
    <module>club-subject-application</module>
    <module>club-subject-domain</module>
    <module>club-subject-starter</module>
    <module>club-subject-common</module>
    <module>club-subject-infra</module>
    <module>club-subject-application/club-subject-application-controller</module>
    <module>club-subject-application/club-subject-application-job</module>
    <module>club-subject-application/club-subject-application-mq</module>
  </modules>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>3.2.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <repositories>
    <repository>
      <id>central</id>
      <name>aliyun maven</name>
<!--      <url>http://maven.aliyun.com/nexus/content/groups/public/</url>-->
      <url>https://maven.aliyun.com/repository/public</url>
      <layout>default</layout>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>

</project>
